### ISSUE TITLE
bitbake xbmc-image (Daisy branch)

### ISSUE THREAD

**Issue by sisao** [wolfgar/meta-stef#3]
Hi,

I try to build your xbmc-image with an adapted version of your https://github.com/wolfgar/fsl-community-bsp-platform .

Compiling is working fine so far, but at the end something is going wrong with installing the u-boot bootloader, I think...
Maybe you can give me a hint, what's the problem...

https://gist.github.com/sisao/2b0a642103ff2082443d#file-log-do_rootfs-3648

https://gist.github.com/sisao/1e0f92b5a873ca572b4c#file-create_image-sdcard

Regards,
Stefan

**Comment by wolfgar** [comment]
Hi
what is you target ? A wandboard ?
you seemed to have grabbed a hack I have done for utilite to push into rfs a u-boot env that will allow to boot from ssd 
in meta-stef/recipes-bsp/u-boot/u-boot-utilite_2009.08.bb
remove 

```
inherit deploy

do_install_append_mx6 () {
  uboot-mkimage -A arm -T script -C none -d ${WORKDIR}/env.txt ${WORKDIR}/bootscript-${MACHINE} 
}

do_deploy_append_mx6 () {
    install -d ${DEPLOYDIR}
    install ${WORKDIR}/bootscript-${MACHINE} \
            ${DEPLOYDIR}/bootscript-${MACHINE}
}

addtask deploy after do_install 
```

you shouldn't need it...

**Comment by sisao** [comment]
Thx for your help.
Yes, a wandboard-quad.
I get it booting up now, I just deleted boot.scr.
Xbmc starts but the screen is grey and shifted... have you seen this before?

I created a uEnv.txt file but it seems that it's ignored.

Regards,
Stefan

**Comment by alfonsotames** [comment]
Does it look like this?

There is a problem with the EGL driver in the Wandboard 3.10.17 kernel.
![q__lozwni3fmjouuybjf_kekwkpz6invqhaxsuuitdm](https://cloud.githubusercontent.com/assets/1441474/4315072/13fdb608-3eed-11e4-9518-0ffe36b9037c.jpeg)

**Comment by sisao** [comment]
yeah, looks exactly like that...
thx for the response...

**Comment by wolfgar** [comment]
It may only be a bad entry in dts for hdmi ... I think I had exactly the same issue long time ago and solved the issue that way

**Comment by alfonsotames** [comment]
Thanks Stephan, I am looking in the wandboard dts right now and comparing it to other imx boards but nothing seems to be out of place (I'm no expert though).

Can you remember what to look for? This problem is occurring to both LCD and HDMI.

Thanks,

Alfonso

**Comment by alfonsotames** [comment]
I found it. Running fbset to set bit depth to 32 bits solved it in HDMI and LCD.

Thanks!

**Comment by wolfgar** [comment]
you are welcome
using fbset is a dynamic way of doing it
in dts you can have this as the default values 
In file arch/arm/boot/dts/imx6qdl-wandboard.dtsi
you can change 

```
mxcfb1: fb@0 {
...
default_bpp = <24>;
..}
```

to 

```
mxcfb1: fb@0 {
...
default_bpp = <32>;
..}
```

**Comment by alfonsotames** [comment]
Stephan,

This is getting stranger. I thought that it worked but it didn't. Now when it try to set it to 32 bits the vivante egl demos still look distorted and sometimes when I ctrl-c the demo the image looks fine!

I am attaching a video:

**Comment by alfonsotames** [comment]
https://www.youtube.com/watch?v=uGpbdHfBS7A&feature=youtu.be

**Comment by alfonsotames** [comment]
OK. I finally found what's happening. Basically, if you boot wandboard 3.10.17 and start an EGL application, it will be distorted since the bit depth is set by default to 24 bits. You won't be able to set correcty the video mode using fbset after running an EGL program. In order to set the video mode correctly, you have to run fbset and set the bit depth to 32bits BEFORE running any EGL application.

Thanks for everything, this situation has been very confusing.
